### PR TITLE
Runtime 44 + Release version 0.4.2

### PR DESCRIPTION
**Pull request by bbhtt**

### CODE REVIEW

**Comment by JamiKettunen** [comment]
Would you mind bumping this? The test build above appears to 404 now. Ping @mjakeman for review? :)

**Comment by bbhtt** [comment]
bot, build

**Comment by mjakeman** [comment]
Hey, thanks for this PR (and sorry it took me so long to get to it!)

I've tagged a new release of extension manager with a lot of translation updates, so I've pushed a commit upgrading that as well. Once it's built, let's merge this.

**Comment by mjakeman** [comment]
bot, build

**Pull request merged**
